#!/usr/bin/bash

rm ~/.inputrc
rm ~/.vim
rm ~/.xmonad
rm ~/.bashrc

ln -s ~/dotfiles/bashrc ~/.bashrc
ln -s ~/dotfiles/inputrc ~/.inputrc
ln -s ~/dotfiles/vim ~/.vim
ln -s ~/dotfiles/xmonad ~/.xmonad
