"   Do not try to be vi-compatible. Also wipe on reload sensibly
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim
set nocompatible
"   
"   ------------------------------------------------------------
"       Plugin management
"   ------------------------------------------------------------
"
call plug#begin()

Plug 'github/copilot.vim'
Plug 'lervag/vimtex'
Plug 'morhetz/gruvbox'

call plug#end()
"
"   ------------------------------------------------------------
"       Set commands
"   ------------------------------------------------------------


"   Allow for indenting and plugins as appropriate
filetype on
filetype indent on
filetype plugin on

"   Allow for syntax highlighting appropriately
syntax enable

"   Default colour scheme to gruvbox
if (empty($TMUX)) && (has('termguicolors'))
  set termguicolors
endif
if (has('termguicolors'))
  set background=light
endif
colorscheme gruvbox

"   Change how files are read into buffers
set autoread        "   Allow silent reloading of buffered files changed outside of vim (e.g. git checkout branch)
set path+=**        "   For finding in entire project context
set dir=~/tmp/vim/swap/,.
set sessionoptions+=sesdir=~/tmp/vim/session/

"   Change how the bottom bar looks and behaves
set wildmenu        "   Allow for tab completion of commands
set showcmd         "   Show the in-progress command buffer
"set laststatus=2    "   Command area is 2 lines high

"   Change how tabs work
set tabstop=2       "   Tabs are -4- 2 spaces
set shiftwidth=2
set expandtab       "   Tabs always expand to spaces
set autoindent      "   Vim will try to indent new lines correctly

"   Change how searching works  
set nohlsearch      "   No highlighted search results
set incsearch       "   Search incrementally (i.e. before enter is pressed)
set wildmode=list:longest

"   Change how moving around the page and counting works
set scrolloff=8     "   Scrolling will begin when cursor is 8 lines from top/bottom
set number          "   The current line is numbered
set relativenumber  "   The other lines are numbered relative to current
set ruler           "   Cursor position located in cmd bar

"   Change some other bits of behaviour
set lazyredraw      "   Screen will not redraw while macros are running
set foldcolumn=0    "   Extra left margin

"   Change some of the page geometry and widths
set textwidth=120   "   Gives a wider default wrapping width
set colorcolumn=0   "   Gives a visual border to the text width
set nowrap          "   Prevent long lines from wrapping (annoying in JSON)
"highlight ColorColumn ctermbg=lightgreen guibg=blue

"   I hate having actual text disappear on me
set conceallevel=0

let mapleader = "\<Space>"
let maplocalleader = "\<Space>"

"   ------------------------------------------------------------
"       VimTex customisation options
"   ------------------------------------------------------------
"
let g:vimtex_view_method = 'zathura'

"   Fuck you tmux and screen
let is_tmux_session = 0
if &term =~ "^screen"
  let is_tmux_session = 1
elseif &term =~ "^tmux"
  let is_tmux_session = 1
endif

if is_tmux_session
  execute "set <xUp>=\e[1;*A"
  execute "set <xDown>=\e[1;*B"
  execute "set <xRight>=\e[1;*C"
  execute "set <xLeft>=\e[1;*D"
endif

"   Readjusting some things
nnoremap Y y$
