unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim
set nocompatible

call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

set background=dark
colorscheme retrobox

filetype plugin indent on
syntax enable
set omnifunc=syntaxcomplete#Complete

packadd! termdebug
let g:termdebug_wide = 163

set autoread lazyredraw modeline
set path+=**
set splitbelow
set wildmenu wildmode=list:longest
set number relativenumber
set showcmd laststatus=2 ruler scrolloff=8
set tabstop=4 shiftwidth=4 expandtab autoindent
set nohlsearch incsearch
set textwidth=88 colorcolumn=90 nowrap conceallevel=0

let &t_SI .= "\e[5 q"
let &t_SR .= "\e[3 q"
let &t_EI .= "\e[2 q"
let g:vimtex_view_method = 'zathura'

command VerticalTerminal execute 'vertical topleft terminal ++cols=' . max([&columns/3, 90]) | set winfixwidth
command HorizontalTerminal execute 'botright terminal ++rows=' . max([&lines/6, 12]) | set winfixheight
command Header execute 'find ' . substitute(expand("%:t"), "\.c$", ".h", "")
command Source execute 'find ' . substitute(expand("%:t"), "\.h$", ".c", "")
command LatexCompile execute expand('!pdflatex -output-directory %:h % && zathura ') . substitute(expand("%"), "\.tex$", ".pdf", "")

nnoremap <Leader>H :Header<CR>
nnoremap <Leader>C :Source<CR>
nnoremap <Leader>L :LatexCompile<CR>
